// Public hooks for themes (docs/themes.md): an imported theme targets these data-ui="..."
// attributes (CSS module class names change from one version to the next, these do not). Set next
// to them: data-kind (kind of card or reader), data-universe (movies, series, music, books, photos,
// collections, playlists, party), data-variant (button), data-tone (message), data-shape (image),
// data-page (section shown), and the ARIA states (aria-current, aria-selected, aria-pressed,
// aria-expanded, disabled). A test checks that this list and the code agree, and that the theme
// authors' guide (docs/themes.md) lists them all.

export const hooks = {
  // Shell
  app: "Shell of the signed-in app: header, content, music player.",
  header: "Header: logo, sections, search, profile.",
  "home-link": "Logo link to the home page.",
  logo: "Laterna brand (dots and name).",
  nav: "Navigation: header sections, administration menu.",
  "nav-link": 'A section (aria-current="page" when shown; data-universe).',
  "nav-more": '"More" button of the secondary sections (aria-expanded).',
  menu: 'Drop-down menu ("More", profile).',
  "menu-item": "Item of a drop-down menu.",
  "header-tools": "Search, notifications and profile group, on the right of the header.",
  "tab-bar": "Phones: bar of the sections at the bottom of the screen, instead of the header's.",
  "tab-bar-link": 'A section of the bar (aria-current="page" when shown; data-universe).',
  "tab-bar-more": '"More" button of the bar: the other sections (aria-expanded).',
  "search-button": "Search button of the header.",
  "notifications-button": 'Bell of the header, to the notifications (aria-current="page" when shown).',
  "profile-button": "Profile badge that opens its menu.",
  main: "Page content (data-page: home, movies, series, music, bookshelf, photos, admin...).",
  "skip-link": '"Skip to content" link, visible with the keyboard.',
  entry: "Entry pages: setup, login, profile choice, device pairing (data-page).",
  "profile-tile": 'A profile on the "Who\'s watching?" page.',
  // Base components
  button: "Button (data-variant: primary, secondary, quiet).",
  field: "Input with its label.",
  switch: "Switch with its label.",
  alert: "Error or information message (data-tone: danger, info).",
  dialog: "Modal dialog.",
  panel: "Card surface of form screens.",
  avatar: "Profile badge (data-universe).",
  artwork: "Catalog image (data-shape: poster, cover, disc, round, photo...).",
  badge: "Small mark on a card or a button: watched, favorite, episode, release date, unread count.",
  progress: "Progress bar over an image.",
  chip: "Filter chip: library, genre (aria-pressed).",
  actions: "Row of buttons of a detail page or a panel.",
  // Home
  home: "Home page.",
  "home-intro": "Greeting and summary of the home page.",
  "home-block": "Home block: one row, or rows in tabs.",
  "block-head": 'Head of a block: title, tabs, "See all", arrows.',
  "block-title": "Title of a block.",
  tabs: "Tabs of a block (role=tablist).",
  tab: "A tab (aria-selected; data-universe).",
  strip: "Scrolling strip of cards.",
  "strip-arrow": "Arrow that scrolls a strip (disabled at the edge).",
  "see-all": '"See all" link.',
  // Lists and cards
  browse: "List page of a section (movies, series, music, books).",
  "page-header": "Page header (data-universe when it has one).",
  filters: "Sort and filters of a list.",
  grid: "Grid of cards.",
  "load-more": 'Counter and "Show more" button.',
  card: "Card (data-kind: movie, series, episode, resume, album, artist, book, book-series, photo, collection, playlist, upcoming; data-universe).",
  "card-title": "Title of a card.",
  "card-meta": "Secondary line of a card.",
  "card-play": "Play button on a card.",
  "side-panel": "Side panel of a page: chosen book, playlists.",
  // Detail pages
  "detail-hero": "Top of a detail page (movie, series, episode; data-universe).",
  "detail-backdrop": "Backdrop image of a detail page.",
  "detail-card": "Card of a detail page: poster, title, overview, buttons.",
  "detail-section": "Section of a detail page: episodes, cast, files.",
  cast: "Cast.",
  "episode-list": "Episodes of a season.",
  episode: "An episode of the list.",
  // Music
  "track-list": "List of tracks.",
  track: "A track (aria-current while it plays).",
  "mini-player": "Floating music player.",
  queue: "Music queue.",
  seek: "Seek bar (video, music).",
  // Photos
  "photo-day": "A day of the photo timeline.",
  "photo-grid": "Justified rows of photos.",
  viewer: "Photo viewer.",
  "viewer-top": "Top of the viewer.",
  "viewer-panel": "Information about a photo.",
  "viewer-strip": "Strip of neighboring photos.",
  // Video and book reading
  player: "Full-screen video player.",
  "player-top": "Top of the player: back, title.",
  "player-bottom": "Bottom of the player: seek bar, controls.",
  "player-controls": "Player controls.",
  "player-panel": "Player panel: audio and subtitles, episodes.",
  reader: "Book reader (data-kind: epub, pages).",
  "reader-top": "Top of the reader.",
  "reader-panel": "Reader panel: settings, table of contents.",
  // Collections, playlists, watch parties, account, administration
  "playlist-entry": "An entry of a playlist.",
  "party-stage": "Picture of a watch party.",
  "party-panel": "Panel of a watch party: members, queue, chat.",
  chat: "Chat of a watch party.",
  download: "A downloaded file.",
  notification: "A notification of the list (data-unread while it is not read).",
  "theme-picker": 'Theme choice in "My account".',
  admin: "Administration: sidebar and content.",
  "admin-side": "Administration sidebar.",
  "admin-menu-button": "Narrow screens: button that opens the administration menu (aria-expanded).",
} as const;

export type Hook = keyof typeof hooks;
