/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppOfflineRouteImport } from './routes/_app/offline'
import { Route as AppPartyRouteImport } from './routes/_app/party'
import { Route as AppPlaylistsRouteImport } from './routes/_app/playlists'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppAccountHistoryRouteImport } from './routes/_app/account/history'
import { Route as AppAccountSecurityRouteImport } from './routes/_app/account/security'
import { Route as AppAccountStatsRouteImport } from './routes/_app/account/stats'
import { Route as AppAccountYearInReviewRouteImport } from './routes/_app/account/year-in-review'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAccountsRouteImport } from './routes/_app/admin/accounts'
import { Route as AppAdminActivityRouteImport } from './routes/_app/admin/activity'
import { Route as AppAdminAuthenticationRouteImport } from './routes/_app/admin/authentication'
import { Route as AppAdminBackupsRouteImport } from './routes/_app/admin/backups'
import { Route as AppAdminDevicesRouteImport } from './routes/_app/admin/devices'
import { Route as AppAdminJellyfinImportRouteImport } from './routes/_app/admin/jellyfin-import'
import { Route as AppAdminLibrariesRouteImport } from './routes/_app/admin/libraries'
import { Route as AppAdminLogsRouteImport } from './routes/_app/admin/logs'
import { Route as AppAdminObservabilityRouteImport } from './routes/_app/admin/observability'
import { Route as AppAdminRequestsRouteImport } from './routes/_app/admin/requests'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminSonarrRadarrRouteImport } from './routes/_app/admin/sonarr-radarr'
import { Route as AppAdminTasksRouteImport } from './routes/_app/admin/tasks'
import { Route as AppAdminThemesRouteImport } from './routes/_app/admin/themes'
import { Route as AppBookshelfIndexRouteImport } from './routes/_app/bookshelf/index'
import { Route as AppEpisodesIdRouteImport } from './routes/_app/episodes/$id'
import { Route as AppMoviesIndexRouteImport } from './routes/_app/movies/index'
import { Route as AppMoviesIdRouteImport } from './routes/_app/movies/$id'
import { Route as AppMusicIndexRouteImport } from './routes/_app/music/index'
import { Route as AppPhotosIndexRouteImport } from './routes/_app/photos/index'
import { Route as AppSeriesIndexRouteImport } from './routes/_app/series/index'
import { Route as AppSeriesIdRouteImport } from './routes/_app/series/$id'
import { Route as AppBookshelfSeriesIdRouteImport } from './routes/_app/bookshelf/series/$id'
import { Route as AppMusicAlbumsIdRouteImport } from './routes/_app/music/albums/$id'
import { Route as AppMusicArtistsIdRouteImport } from './routes/_app/music/artists/$id'
import { Route as AppPhotosAlbumsIdRouteImport } from './routes/_app/photos/albums/$id'
import { Route as AppPlayBookIdRouteImport } from './routes/_app/play/book/$id'
import { Route as AppPlayEpisodeIdRouteImport } from './routes/_app/play/episode/$id'
import { Route as AppPlayMovieIdRouteImport } from './routes/_app/play/movie/$id'
import { Route as AppPlayPartyIdRouteImport } from './routes/_app/play/party/$id'
import { Route as AppPlayPhotoIdRouteImport } from './routes/_app/play/photo/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const AppPartyRoute = AppPartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountHistoryRoute = AppAccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountStatsRoute = AppAccountStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountYearInReviewRoute = AppAccountYearInReviewRouteImport.update({
  id: '/year-in-review',
  path: '/year-in-review',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAccountsRoute = AppAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuthenticationRoute = AppAdminAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupsRoute = AppAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDevicesRoute = AppAdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminJellyfinImportRoute = AppAdminJellyfinImportRouteImport.update({
  id: '/jellyfin-import',
  path: '/jellyfin-import',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLibrariesRoute = AppAdminLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminObservabilityRoute = AppAdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSonarrRadarrRoute = AppAdminSonarrRadarrRouteImport.update({
  id: '/sonarr-radarr',
  path: '/sonarr-radarr',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTasksRoute = AppAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminThemesRoute = AppAdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppBookshelfIndexRoute = AppBookshelfIndexRouteImport.update({
  id: '/bookshelf/',
  path: '/bookshelf/',
  getParentRoute: () => AppRoute,
} as any)
const AppEpisodesIdRoute = AppEpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIdRoute = AppMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicIndexRoute = AppMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosIndexRoute = AppPhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIdRoute = AppSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookshelfSeriesIdRoute = AppBookshelfSeriesIdRouteImport.update({
  id: '/bookshelf/series/$id',
  path: '/bookshelf/series/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicAlbumsIdRoute = AppMusicAlbumsIdRouteImport.update({
  id: '/music/albums/$id',
  path: '/music/albums/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicArtistsIdRoute = AppMusicArtistsIdRouteImport.update({
  id: '/music/artists/$id',
  path: '/music/artists/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosAlbumsIdRoute = AppPhotosAlbumsIdRouteImport.update({
  id: '/photos/albums/$id',
  path: '/photos/albums/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayBookIdRoute = AppPlayBookIdRouteImport.update({
  id: '/play/book/$id',
  path: '/play/book/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayEpisodeIdRoute = AppPlayEpisodeIdRouteImport.update({
  id: '/play/episode/$id',
  path: '/play/episode/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayMovieIdRoute = AppPlayMovieIdRouteImport.update({
  id: '/play/movie/$id',
  path: '/play/movie/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayPartyIdRoute = AppPlayPartyIdRouteImport.update({
  id: '/play/party/$id',
  path: '/play/party/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayPhotoIdRoute = AppPlayPhotoIdRouteImport.update({
  id: '/play/photo/$id',
  path: '/play/photo/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/profiles': typeof ProfilesRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/collections': typeof AppCollectionsRoute
  '/discover': typeof AppDiscoverRoute
  '/offline': typeof AppOfflineRoute
  '/party': typeof AppPartyRoute
  '/playlists': typeof AppPlaylistsRoute
  '/requests': typeof AppRequestsRoute
  '/search': typeof AppSearchRoute
  '/account/history': typeof AppAccountHistoryRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/account/stats': typeof AppAccountStatsRoute
  '/account/year-in-review': typeof AppAccountYearInReviewRoute
  '/admin/accounts': typeof AppAdminAccountsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/authentication': typeof AppAdminAuthenticationRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/devices': typeof AppAdminDevicesRoute
  '/admin/jellyfin-import': typeof AppAdminJellyfinImportRoute
  '/admin/libraries': typeof AppAdminLibrariesRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/observability': typeof AppAdminObservabilityRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sonarr-radarr': typeof AppAdminSonarrRadarrRoute
  '/admin/tasks': typeof AppAdminTasksRoute
  '/admin/themes': typeof AppAdminThemesRoute
  '/episodes/$id': typeof AppEpisodesIdRoute
  '/movies/$id': typeof AppMoviesIdRoute
  '/series/$id': typeof AppSeriesIdRoute
  '/account/': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/bookshelf/': typeof AppBookshelfIndexRoute
  '/movies/': typeof AppMoviesIndexRoute
  '/music/': typeof AppMusicIndexRoute
  '/photos/': typeof AppPhotosIndexRoute
  '/series/': typeof AppSeriesIndexRoute
  '/bookshelf/series/$id': typeof AppBookshelfSeriesIdRoute
  '/music/albums/$id': typeof AppMusicAlbumsIdRoute
  '/music/artists/$id': typeof AppMusicArtistsIdRoute
  '/photos/albums/$id': typeof AppPhotosAlbumsIdRoute
  '/play/book/$id': typeof AppPlayBookIdRoute
  '/play/episode/$id': typeof AppPlayEpisodeIdRoute
  '/play/movie/$id': typeof AppPlayMovieIdRoute
  '/play/party/$id': typeof AppPlayPartyIdRoute
  '/play/photo/$id': typeof AppPlayPhotoIdRoute
}
export interface FileRoutesByTo {
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/profiles': typeof ProfilesRoute
  '/setup': typeof SetupRoute
  '/collections': typeof AppCollectionsRoute
  '/discover': typeof AppDiscoverRoute
  '/offline': typeof AppOfflineRoute
  '/party': typeof AppPartyRoute
  '/playlists': typeof AppPlaylistsRoute
  '/requests': typeof AppRequestsRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/account/history': typeof AppAccountHistoryRoute
  '/account/security': typeof AppAccountSecurityRoute
  '/account/stats': typeof AppAccountStatsRoute
  '/account/year-in-review': typeof AppAccountYearInReviewRoute
  '/admin/accounts': typeof AppAdminAccountsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/authentication': typeof AppAdminAuthenticationRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/devices': typeof AppAdminDevicesRoute
  '/admin/jellyfin-import': typeof AppAdminJellyfinImportRoute
  '/admin/libraries': typeof AppAdminLibrariesRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/observability': typeof AppAdminObservabilityRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sonarr-radarr': typeof AppAdminSonarrRadarrRoute
  '/admin/tasks': typeof AppAdminTasksRoute
  '/admin/themes': typeof AppAdminThemesRoute
  '/episodes/$id': typeof AppEpisodesIdRoute
  '/movies/$id': typeof AppMoviesIdRoute
  '/series/$id': typeof AppSeriesIdRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/bookshelf': typeof AppBookshelfIndexRoute
  '/movies': typeof AppMoviesIndexRoute
  '/music': typeof AppMusicIndexRoute
  '/photos': typeof AppPhotosIndexRoute
  '/series': typeof AppSeriesIndexRoute
  '/bookshelf/series/$id': typeof AppBookshelfSeriesIdRoute
  '/music/albums/$id': typeof AppMusicAlbumsIdRoute
  '/music/artists/$id': typeof AppMusicArtistsIdRoute
  '/photos/albums/$id': typeof AppPhotosAlbumsIdRoute
  '/play/book/$id': typeof AppPlayBookIdRoute
  '/play/episode/$id': typeof AppPlayEpisodeIdRoute
  '/play/movie/$id': typeof AppPlayMovieIdRoute
  '/play/party/$id': typeof AppPlayPartyIdRoute
  '/play/photo/$id': typeof AppPlayPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/profiles': typeof ProfilesRoute
  '/setup': typeof SetupRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/offline': typeof AppOfflineRoute
  '/_app/party': typeof AppPartyRoute
  '/_app/playlists': typeof AppPlaylistsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/history': typeof AppAccountHistoryRoute
  '/_app/account/security': typeof AppAccountSecurityRoute
  '/_app/account/stats': typeof AppAccountStatsRoute
  '/_app/account/year-in-review': typeof AppAccountYearInReviewRoute
  '/_app/admin/accounts': typeof AppAdminAccountsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/authentication': typeof AppAdminAuthenticationRoute
  '/_app/admin/backups': typeof AppAdminBackupsRoute
  '/_app/admin/devices': typeof AppAdminDevicesRoute
  '/_app/admin/jellyfin-import': typeof AppAdminJellyfinImportRoute
  '/_app/admin/libraries': typeof AppAdminLibrariesRoute
  '/_app/admin/logs': typeof AppAdminLogsRoute
  '/_app/admin/observability': typeof AppAdminObservabilityRoute
  '/_app/admin/requests': typeof AppAdminRequestsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/sonarr-radarr': typeof AppAdminSonarrRadarrRoute
  '/_app/admin/tasks': typeof AppAdminTasksRoute
  '/_app/admin/themes': typeof AppAdminThemesRoute
  '/_app/episodes/$id': typeof AppEpisodesIdRoute
  '/_app/movies/$id': typeof AppMoviesIdRoute
  '/_app/series/$id': typeof AppSeriesIdRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/bookshelf/': typeof AppBookshelfIndexRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
  '/_app/music/': typeof AppMusicIndexRoute
  '/_app/photos/': typeof AppPhotosIndexRoute
  '/_app/series/': typeof AppSeriesIndexRoute
  '/_app/bookshelf/series/$id': typeof AppBookshelfSeriesIdRoute
  '/_app/music/albums/$id': typeof AppMusicAlbumsIdRoute
  '/_app/music/artists/$id': typeof AppMusicArtistsIdRoute
  '/_app/photos/albums/$id': typeof AppPhotosAlbumsIdRoute
  '/_app/play/book/$id': typeof AppPlayBookIdRoute
  '/_app/play/episode/$id': typeof AppPlayEpisodeIdRoute
  '/_app/play/movie/$id': typeof AppPlayMovieIdRoute
  '/_app/play/party/$id': typeof AppPlayPartyIdRoute
  '/_app/play/photo/$id': typeof AppPlayPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/login'
    | '/profiles'
    | '/setup'
    | '/account'
    | '/admin'
    | '/collections'
    | '/discover'
    | '/offline'
    | '/party'
    | '/playlists'
    | '/requests'
    | '/search'
    | '/account/history'
    | '/account/security'
    | '/account/stats'
    | '/account/year-in-review'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/authentication'
    | '/admin/backups'
    | '/admin/devices'
    | '/admin/jellyfin-import'
    | '/admin/libraries'
    | '/admin/logs'
    | '/admin/observability'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/sonarr-radarr'
    | '/admin/tasks'
    | '/admin/themes'
    | '/episodes/$id'
    | '/movies/$id'
    | '/series/$id'
    | '/account/'
    | '/admin/'
    | '/bookshelf/'
    | '/movies/'
    | '/music/'
    | '/photos/'
    | '/series/'
    | '/bookshelf/series/$id'
    | '/music/albums/$id'
    | '/music/artists/$id'
    | '/photos/albums/$id'
    | '/play/book/$id'
    | '/play/episode/$id'
    | '/play/movie/$id'
    | '/play/party/$id'
    | '/play/photo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/device'
    | '/login'
    | '/profiles'
    | '/setup'
    | '/collections'
    | '/discover'
    | '/offline'
    | '/party'
    | '/playlists'
    | '/requests'
    | '/search'
    | '/'
    | '/account/history'
    | '/account/security'
    | '/account/stats'
    | '/account/year-in-review'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/authentication'
    | '/admin/backups'
    | '/admin/devices'
    | '/admin/jellyfin-import'
    | '/admin/libraries'
    | '/admin/logs'
    | '/admin/observability'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/sonarr-radarr'
    | '/admin/tasks'
    | '/admin/themes'
    | '/episodes/$id'
    | '/movies/$id'
    | '/series/$id'
    | '/account'
    | '/admin'
    | '/bookshelf'
    | '/movies'
    | '/music'
    | '/photos'
    | '/series'
    | '/bookshelf/series/$id'
    | '/music/albums/$id'
    | '/music/artists/$id'
    | '/photos/albums/$id'
    | '/play/book/$id'
    | '/play/episode/$id'
    | '/play/movie/$id'
    | '/play/party/$id'
    | '/play/photo/$id'
  id:
    | '__root__'
    | '/_app'
    | '/device'
    | '/login'
    | '/profiles'
    | '/setup'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/collections'
    | '/_app/discover'
    | '/_app/offline'
    | '/_app/party'
    | '/_app/playlists'
    | '/_app/requests'
    | '/_app/search'
    | '/_app/'
    | '/_app/account/history'
    | '/_app/account/security'
    | '/_app/account/stats'
    | '/_app/account/year-in-review'
    | '/_app/admin/accounts'
    | '/_app/admin/activity'
    | '/_app/admin/authentication'
    | '/_app/admin/backups'
    | '/_app/admin/devices'
    | '/_app/admin/jellyfin-import'
    | '/_app/admin/libraries'
    | '/_app/admin/logs'
    | '/_app/admin/observability'
    | '/_app/admin/requests'
    | '/_app/admin/settings'
    | '/_app/admin/sonarr-radarr'
    | '/_app/admin/tasks'
    | '/_app/admin/themes'
    | '/_app/episodes/$id'
    | '/_app/movies/$id'
    | '/_app/series/$id'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/bookshelf/'
    | '/_app/movies/'
    | '/_app/music/'
    | '/_app/photos/'
    | '/_app/series/'
    | '/_app/bookshelf/series/$id'
    | '/_app/music/albums/$id'
    | '/_app/music/artists/$id'
    | '/_app/photos/albums/$id'
    | '/_app/play/book/$id'
    | '/_app/play/episode/$id'
    | '/_app/play/movie/$id'
    | '/_app/play/party/$id'
    | '/_app/play/photo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  ProfilesRoute: typeof ProfilesRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offline': {
      id: '/_app/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/party': {
      id: '/_app/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof AppPartyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/history': {
      id: '/_app/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AppAccountHistoryRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/security': {
      id: '/_app/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/stats': {
      id: '/_app/account/stats'
      path: '/stats'
      fullPath: '/account/stats'
      preLoaderRoute: typeof AppAccountStatsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/year-in-review': {
      id: '/_app/account/year-in-review'
      path: '/year-in-review'
      fullPath: '/account/year-in-review'
      preLoaderRoute: typeof AppAccountYearInReviewRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/accounts': {
      id: '/_app/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AppAdminAccountsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/authentication': {
      id: '/_app/admin/authentication'
      path: '/authentication'
      fullPath: '/admin/authentication'
      preLoaderRoute: typeof AppAdminAuthenticationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backups': {
      id: '/_app/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AppAdminBackupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/devices': {
      id: '/_app/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AppAdminDevicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/jellyfin-import': {
      id: '/_app/admin/jellyfin-import'
      path: '/jellyfin-import'
      fullPath: '/admin/jellyfin-import'
      preLoaderRoute: typeof AppAdminJellyfinImportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/libraries': {
      id: '/_app/admin/libraries'
      path: '/libraries'
      fullPath: '/admin/libraries'
      preLoaderRoute: typeof AppAdminLibrariesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/logs': {
      id: '/_app/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/observability': {
      id: '/_app/admin/observability'
      path: '/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AppAdminObservabilityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/requests': {
      id: '/_app/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/sonarr-radarr': {
      id: '/_app/admin/sonarr-radarr'
      path: '/sonarr-radarr'
      fullPath: '/admin/sonarr-radarr'
      preLoaderRoute: typeof AppAdminSonarrRadarrRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/tasks': {
      id: '/_app/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AppAdminTasksRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/themes': {
      id: '/_app/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AppAdminThemesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/bookshelf/': {
      id: '/_app/bookshelf/'
      path: '/bookshelf'
      fullPath: '/bookshelf/'
      preLoaderRoute: typeof AppBookshelfIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/episodes/$id': {
      id: '/_app/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/episodes/$id'
      preLoaderRoute: typeof AppEpisodesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$id': {
      id: '/_app/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof AppMoviesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music/': {
      id: '/_app/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof AppMusicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos/': {
      id: '/_app/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof AppPhotosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/': {
      id: '/_app/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/$id': {
      id: '/_app/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof AppSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookshelf/series/$id': {
      id: '/_app/bookshelf/series/$id'
      path: '/bookshelf/series/$id'
      fullPath: '/bookshelf/series/$id'
      preLoaderRoute: typeof AppBookshelfSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music/albums/$id': {
      id: '/_app/music/albums/$id'
      path: '/music/albums/$id'
      fullPath: '/music/albums/$id'
      preLoaderRoute: typeof AppMusicAlbumsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music/artists/$id': {
      id: '/_app/music/artists/$id'
      path: '/music/artists/$id'
      fullPath: '/music/artists/$id'
      preLoaderRoute: typeof AppMusicArtistsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos/albums/$id': {
      id: '/_app/photos/albums/$id'
      path: '/photos/albums/$id'
      fullPath: '/photos/albums/$id'
      preLoaderRoute: typeof AppPhotosAlbumsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/book/$id': {
      id: '/_app/play/book/$id'
      path: '/play/book/$id'
      fullPath: '/play/book/$id'
      preLoaderRoute: typeof AppPlayBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/episode/$id': {
      id: '/_app/play/episode/$id'
      path: '/play/episode/$id'
      fullPath: '/play/episode/$id'
      preLoaderRoute: typeof AppPlayEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/movie/$id': {
      id: '/_app/play/movie/$id'
      path: '/play/movie/$id'
      fullPath: '/play/movie/$id'
      preLoaderRoute: typeof AppPlayMovieIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/party/$id': {
      id: '/_app/play/party/$id'
      path: '/play/party/$id'
      fullPath: '/play/party/$id'
      preLoaderRoute: typeof AppPlayPartyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/photo/$id': {
      id: '/_app/play/photo/$id'
      path: '/play/photo/$id'
      fullPath: '/play/photo/$id'
      preLoaderRoute: typeof AppPlayPhotoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountHistoryRoute: typeof AppAccountHistoryRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppAccountStatsRoute: typeof AppAccountStatsRoute
  AppAccountYearInReviewRoute: typeof AppAccountYearInReviewRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountHistoryRoute: AppAccountHistoryRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppAccountStatsRoute: AppAccountStatsRoute,
  AppAccountYearInReviewRoute: AppAccountYearInReviewRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAccountsRoute: typeof AppAdminAccountsRoute
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminAuthenticationRoute: typeof AppAdminAuthenticationRoute
  AppAdminBackupsRoute: typeof AppAdminBackupsRoute
  AppAdminDevicesRoute: typeof AppAdminDevicesRoute
  AppAdminJellyfinImportRoute: typeof AppAdminJellyfinImportRoute
  AppAdminLibrariesRoute: typeof AppAdminLibrariesRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminObservabilityRoute: typeof AppAdminObservabilityRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSonarrRadarrRoute: typeof AppAdminSonarrRadarrRoute
  AppAdminTasksRoute: typeof AppAdminTasksRoute
  AppAdminThemesRoute: typeof AppAdminThemesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAccountsRoute: AppAdminAccountsRoute,
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminAuthenticationRoute: AppAdminAuthenticationRoute,
  AppAdminBackupsRoute: AppAdminBackupsRoute,
  AppAdminDevicesRoute: AppAdminDevicesRoute,
  AppAdminJellyfinImportRoute: AppAdminJellyfinImportRoute,
  AppAdminLibrariesRoute: AppAdminLibrariesRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminObservabilityRoute: AppAdminObservabilityRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSonarrRadarrRoute: AppAdminSonarrRadarrRoute,
  AppAdminTasksRoute: AppAdminTasksRoute,
  AppAdminThemesRoute: AppAdminThemesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppOfflineRoute: typeof AppOfflineRoute
  AppPartyRoute: typeof AppPartyRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEpisodesIdRoute: typeof AppEpisodesIdRoute
  AppMoviesIdRoute: typeof AppMoviesIdRoute
  AppSeriesIdRoute: typeof AppSeriesIdRoute
  AppBookshelfIndexRoute: typeof AppBookshelfIndexRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
  AppMusicIndexRoute: typeof AppMusicIndexRoute
  AppPhotosIndexRoute: typeof AppPhotosIndexRoute
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
  AppBookshelfSeriesIdRoute: typeof AppBookshelfSeriesIdRoute
  AppMusicAlbumsIdRoute: typeof AppMusicAlbumsIdRoute
  AppMusicArtistsIdRoute: typeof AppMusicArtistsIdRoute
  AppPhotosAlbumsIdRoute: typeof AppPhotosAlbumsIdRoute
  AppPlayBookIdRoute: typeof AppPlayBookIdRoute
  AppPlayEpisodeIdRoute: typeof AppPlayEpisodeIdRoute
  AppPlayMovieIdRoute: typeof AppPlayMovieIdRoute
  AppPlayPartyIdRoute: typeof AppPlayPartyIdRoute
  AppPlayPhotoIdRoute: typeof AppPlayPhotoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCollectionsRoute: AppCollectionsRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppOfflineRoute: AppOfflineRoute,
  AppPartyRoute: AppPartyRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppEpisodesIdRoute: AppEpisodesIdRoute,
  AppMoviesIdRoute: AppMoviesIdRoute,
  AppSeriesIdRoute: AppSeriesIdRoute,
  AppBookshelfIndexRoute: AppBookshelfIndexRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
  AppMusicIndexRoute: AppMusicIndexRoute,
  AppPhotosIndexRoute: AppPhotosIndexRoute,
  AppSeriesIndexRoute: AppSeriesIndexRoute,
  AppBookshelfSeriesIdRoute: AppBookshelfSeriesIdRoute,
  AppMusicAlbumsIdRoute: AppMusicAlbumsIdRoute,
  AppMusicArtistsIdRoute: AppMusicArtistsIdRoute,
  AppPhotosAlbumsIdRoute: AppPhotosAlbumsIdRoute,
  AppPlayBookIdRoute: AppPlayBookIdRoute,
  AppPlayEpisodeIdRoute: AppPlayEpisodeIdRoute,
  AppPlayMovieIdRoute: AppPlayMovieIdRoute,
  AppPlayPartyIdRoute: AppPlayPartyIdRoute,
  AppPlayPhotoIdRoute: AppPlayPhotoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  ProfilesRoute: ProfilesRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
